config/routes.rb
Rails.application.routes.draw do
  get 'rooms/registration'
  get 'mains/index'
  get 'rooms/index'
  get 'reserves/index'
  
  root :to => 'mains#index'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions'
}

  resources :rooms do
    collection do
      get 'search'
    end
  end

  resources :mains
  resources :rooms
  resources :reserves

  get 'search' => 'searches#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_container">
        <div class="header_left">
          <%= link_to image_tag("potelogo.png"), :mains %>
          <%= search_form_for @q do |f| %>
            <ul>
              <li>
                <%= f.search_field :adress_cont, placeholder: "エリア" %>
                <% f.submit %>
              </li>
            </ul>
          <% end %>
          <%= search_form_for @q do |f| %>
            <ul>
              <li>
                <%= f.search_field :introduction_cont, placeholder: "キーワード" %>
                <% f.submit %>
              </li>
            </ul>
          <% end %>
        </div>

        <% if !logged_in? %>
          <div class="header_right">
            <%= link_to new_user_session_path do %>
              <div class="log_in_btn">ログイン</div>
            <% end %>
            
            <%= link_to new_user_registration_path do %>
              <div class="sign_up_btn">新規登録</div>
            <% end %>
          </div>
        <% else %>
          <div class="header_right">
            <% if current_user.image? %>
              <div class="user_name"><%= current_user.name %> さん</div>
              <div class="thumbnail"><%= image_tag current_user.image.to_s, class: 'thumbnail_img' %></div>
            <% else %>
              <div class="thumbnail"><%= image_tag("人物のアイコン素材 その3.png", class: 'thumbnail_img') %></div>
            <% end %>
            <div>
              <div class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler nav-bar-menu">メニュー</span>
              </div>
              <nav class="collapse navbar-collapse" id="navbarNav">
                <ul class="header_menu navbar-nav">
                  <li class="nav-item active">
                    <%= link_to new_room_path do %>
                    ルーム登録
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to reserves_path do %>
                    予約済ルーム一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to rooms_registration_path do %>
                    登録済ルーム一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to edit_user_registration_path do %>
                    編集
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    ログアウト
                    <% end %>
                  </li>
                </ul>
              </nav>
            </div>
        <% end %>
      </div>

    </header>

    <%= yield %>
  
    <p><%= link_to "戻る", :back %></p>
    <p><%= link_to "Topページへ", :mains %></p>

    <div class="wrapper">
      <footer class="footer">
        <p>©︎ 2022 YACHI.INC</p>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>